migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    'FootyStatsMigrations': /app/migrations/footy_stats
connection: footy_stats
